---
title: "2018년 1학기 데이터분석기법과실습 기말고사"
author: "양승훈"
date: '2018 6 16 '
output: html_document
---

## 고생했습니다.
한 학기 익숙하지 않은 프로그래밍과 데이터분석 수업 듣느라 고생했습니다.
마지막 기말고사를 통해서 지금까지 배웠던 내용들을 다시 복기해볼 수 있길 바랍니다.

## 준비
1. tidyverse 패키지가 필요합니다.

library(tidyverse)

2. 4개의 파일이 필요합니다. (인코딩 문제가 있을 때는 read_csv("파일명", locale = locale(encoding = "UTF-8")) 실행)
1) industry.csv [다운로드](https://github.com/harryyang1982/r_social_research/raw/master/industry.csv)
2) industry_tidy.csv [다운로드](https://github.com/harryyang1982/r_social_research/raw/master/industry_tidy.csv)
3) traffic_accident.csv [다운로드](https://github.com/harryyang1982/r_social_research/raw/master/traffic_accident.csv)
4) traffic_reason.csv [다운로드](https://github.com/harryyang1982/r_social_research/raw/master/traffic_reason.csv)

3. Lahman 패키지가 필요합니다.
library(Lahman) (없을 때에는 설치)

## 안내
기말고사 시간은 10:00~11:00까지입니다.

문제는 단답형(5점), 분석형(10점). 그 외 보너스 문제(5점)이 있습니다. 분석형과 보너스 문제는 코드 전체를 적어서 내는 것입니다.

제출은 RMarkdown이나 #를 활용하여 .r 파일로 제출할 수 있습니다.

## 단답형(총 5점)
1. mpg 데이터의 class 변수의 값에 **따라** hwy 변수값의 중위값을 확인하기 위해 필요한 명령어를 쓰시오. (0.5점)
2. 전역 변수(global variable)과 지역 변수(local variable)의 차이를 간단히 쓰시오 (1점)
3. geom_smooth()로 추세선을 그릴 때 **선형회귀**를 구현하기 위한 방식으로 써보시오. (0.5점)
4. mpg 데이터에서 cty 변수만 보고 싶을 때 실행하는 명령어는? (0.5점)
5. mpg 데이터에서 class를 맨 앞에 놓고 나머지 전체를 그 뒤에 배치하고 싶을 때 실행하는 명령어는? (0.5점)
6. mpg 데이터에서 class 변수의 값 중 c("suv", "pickup")에 포함되는 내용만 추리고 싶을 때 실행하는 명령어는? (0.5점)
7. flights 데이터를 arr_delay 열을 기준으로 내림차순 정렬하고 싶을 때 실행하는 명령어는? (0.5점)
8. Batting 데이터를 가지고 AVG열을 만들어 보시오 (H/AB) (0.5점)
9. mpg 데이터에서 각 class별 갯수를 구하는 명령어는? (0.5점)


## 심화형(총 10점)

1. mpg 데이터의 displ, hwy간의 관계를 점 그래프(산점도)로 구현해 보려고 한다. (x=displ, y=hwy)

1-1. manufacturer에 따른 색깔 변화를 주기 위한 명령어는? (0.5점)

1-2. class에 따른 모양 변화를 주기 위한 명령어는? (0.5점)

1-3. 그래프의 색깔을 "red"로 하고 싶을 때의 명령어는? (0.5점)


2. nycflights 패키지의 flights 데이터를 활용하여 답변하시오.

2-1. dep_delay가 0보다 크거나 같은 것들을 추리는 명령어는? (0.5점)

2-2. dep_delay가 0보다 크거나 같은 곳을 추린 후, dest에 따른 arr_delay의 평균을 구해보시오. (1점)

2-3. 월별 비행편수를 구해보시오. (1점)


3. Lahman 패키지의 Batting 데이터를 활용하여 답변하시오.

3-1. 최다 도루(SB)를 기록한 타자는? (1점)

3-2. 최다 2루타(X2B를 기록한 타자는? (1점)


4. traffic_accident 데이터와 traffic_reason 데이터를 가지고 다음에 답변하시오.

4-1. 전체 교통 사고는 줄어들고 있는가, 늘어나고 있는가? 그래프로 표현하시오. (2점)

4-2. 가장 빈번한 교통 사고의 이유는 무엇인가? 그래프로 표현한 후 답하시오. (1점)

4-3. 가장 빈번한 교통 사고의 이유로 지목된 요인의 추세를 시계열로 표현하시오. (1점)


## 보너스 문제(총 5점)
1. industry 데이터를 industry_tidy로 바꾸는 명령어는? (2점)
2. industry_tidy 데이터를 industry 데이터로 돌려놓기 위한 명령어는? (2점)
3. table3 (tidyverse에 포함되어 있음)의 rate 데이터를 'cases', 'population'으로 쪼개서 table_tidy에 저장하시오. (1점)